/persistency/gdml/read /usr/local/data/detectors/ldmx-det-full-v9-fieldmap/detector.gdml
/ldmx/pw/enable 
/ldmx/pw/read /usr/local/data/detectors/scoring_planes/detector.gdml
/ldmx/biasing/enable
/ldmx/biasing/particle gamma
/ldmx/biasing/process GammaToMuPair
/ldmx/biasing/volume ecal
/ldmx/biasing/threshold 5000
/run/initialize
/ldmx/biasing/xsec/particle gamma
/ldmx/biasing/xsec/threshold 5000
/ldmx/biasing/xsec/factor 30000
/gun/particle e-
/gun/energy 8.0 GeV
/gun/position 0. 0. -1.2 mm
/gun/direction 0. 0. 8.0 GeV
/ldmx/plugins/load EventPrintPlugin
/ldmx/plugins/EventPrintPlugin/modulus 20000
/ldmx/plugins/load TargetBremFilter libBiasing.so
/ldmx/plugins/TargetBremFilter/volume target_PV
/ldmx/plugins/TargetBremFilter/recoil_threshold 3000
/ldmx/plugins/TargetBremFilter/brem_threshold 5000
/ldmx/plugins/load EcalProcessFilter libBiasing.so
/ldmx/plugins/EcalProcessFilter/volume ecal
/ldmx/plugins/load TrackFilterPlugin 
/ldmx/plugins/TrackFilterPlugin/process GammaToMuPair true
/ldmx/plugins/TrackFilterPlugin/region CalorimeterRegion true 
/ldmx/plugins/TrackFilterPlugin/create muFilter
/ldmx/generators/beamspot/enable
/ldmx/generators/beamspot/sizeX 20.0
/ldmx/generators/beamspot/sizeY 80.0
/ldmx/persistency/root/dropCol MagnetScoringPlaneHits
/ldmx/persistency/root/dropCol TrackerScoringPlaneHits
/ldmx/persistency/root/dropCol HcalScoringPlaneHits
/ldmx/persistency/root/verbose 0
/ldmx/persistency/root/file ecal_muon.root
/ldmx/persistency/root/description "ECal muon conversion, 8 GeV beam, xsec bias 30000"
/ldmx/persistency/root/runNumber 1
/random/setSeeds 1 2
/random/setSavingFlag 0
/run/beamOn 30000
