services:
  rucio-server:
    image: rucio/rucio-server:release-1.26.11
    hostname: ${LDCS_RUCIO_FQDN}
    ports:
      - "443:443"
    volumes:
      - /etc/grid-security/:/etc/grid-security/
#      - /etc/grid-security/hostcert.pem:/etc/grid-security/hostcert.pem
#      - /etc/grid-security/hostkey.pem:/etc/grid-security/hostkey.pem
      - /opt/rucio/etc:/opt/rucio/etc
      # Added for rucio logs according to https://rucio.github.io/documentation/operator/installing_server
      - /var/log/rucio/httpd:/var/log/httpd
    environment:
      - RUCIO_ENABLE_SSL=True
      - RUCIO_HOSTNAME=${LDCS_RUCIO_FQDN}
      - RUCIO_CFG_DATABASE_DEFAULT=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ruciodb/${POSTGRES_DB}
      - RUCIO_CA_PATH=/etc/grid-security/certificates
      - RUCIO_ENABLE_LOGFILE=True
  ruciodb:
    image: postgres:11
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    command: ["-c", "fsync=off","-c", "synchronous_commit=off","-c", "full_page_writes=off"]
    volumes:
      - vol-ruciodb-data:/var/lib/postgresql/data
   rucio-daemons-abacus:
     image: rucio/rucio-daemons:release-1.26.11
     volumes:
       - /opt/rucio/etc/rucio.cfg:/opt/rucio/etc/rucio.cfg
       # comment out the following to use docker compose logs only. This logs to the host system, when we have space
       - /var/log/rucio:/var/log/rucio
     environment:
       - RUCIO_DAEMON=abacus-rse
       - RUCIO_ENABLE_LOGS=True
   rucio-daemons-reaper:
     image: rucio/rucio-daemons:release-1.26.11
     volumes:
       - /opt/rucio/etc/rucio.cfg:/opt/rucio/etc/rucio.cfg
       - /home/almalinux/act/ldmx.long.proxy.root:/opt/rucio/etc/x509
       - /etc/grid-security/certificates:/etc/grid-security/certificates
       # comment out the following to use docker compose logs only. This logs to the host system, when we have space
       - /var/log/rucio:/var/log/rucio
     environment:
       - RUCIO_DAEMON=reaper
       - RUCIO_ENABLE_LOGS=True 
       - X509_USER_PROXY=/opt/rucio/etc/x509
   rucio-daemons-undertaker:
     image: rucio/rucio-daemons:release-1.26.11
     volumes:
       - /opt/rucio/etc/rucio.cfg:/opt/rucio/etc/rucio.cfg
       # comment out the following to use docker compose logs only. This logs to the host system, when we have space
       - /var/log/rucio:/var/log/rucio
     environment:
      - RUCIO_DAEMON=undertaker
      - RUCIO_ENABLE_LOGS=True

volumes:
  vol-ruciodb-data:

